config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get "/about/" => "pages#about"
  root "pages#home"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
    <div class="col-md-6">
        <div class="col-md-offset-3">
            <h1>Contact Us</h1>
            <p>At Project Novella, it is all about the artists and readers. We greatly appreciate your feedback, so if you have any suggestions, feedback or comments then please feel free to contact us!</p>
            <p class="fine-print">*Please note that this is not a means to report anyone. Refer to your dashboard on how to do that.</p>
            <%= form_for @contact do |f| %>
                <div class="well">
                    <div class="form-group">
                        <%= f.label :name %>
                        <%= f.text_field :name, class: "form-control" %>
                    
                        <%= f.label :email %>
                        <%= f.email_field :email, class: "form-control" %>
                        
                        <%= f.label :comment %>
                        <%= f.text_area :comment, class: "form-control" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectNovella</title>
  <link href='https://fonts.googleapis.com/css?family=Italianno' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Project Novella', root_path, class: 'navbar-brand title' %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Us", new_contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>
</body>
</htm>

app/views/pages/about.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3 white">
        <h2 class="text-center">The Mission</h2>
        <p>Here at Project Novella, we wanted to give Authors a safe, positive space to write and edit their current projects while keeping their readers updated with new content, at their own pace. Imagine writing
        books and short stories in blog format, for free. Push yourself to write a chapter a week and keep your readers hungering for more like they are watching their favorite television series. Why keep your readers waiting
        for months or even years for a new book release when you can give them a little at a time? Maybe you just have a story you want to tell and want a place to tell it, pressure free and have the option to allow readers 
        to give you positive, constructive feedback via an anonymous email or have a place to connect with an artist or publisher.</p>
        <h3>Authors</h3>
            <ul>
                <li>Manage your current projects through your easy to use Author user interface.</li>
                <li>See how often your projects are getting viewed.</li>
                <li>Earn points from your readers for your content and see where you stand on the Author Leaderboard.</li>
            </ul>
        </br>
        <h3>Readers</h3>
            <ul>
                <li>Keep track of what you've read and manage your favorites in our Reader user interface.</li>
                <li>Bookmark projects you are reading through to save your place.</li>
                <li>Earn commendation points to spend by submitting praise and friendly critique to your favorite Authors via an anonymous email.</li>
            </ul>
        </br>
        <h3>Artists, Editors and Publishers</h3>
            <ul>
                <li>See what Authors are getting the most views and positive feedback.</li>
                <li>Reach out and connect to Authors through our Classified Ads section to do business.</li>
            </ul>
    </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
    <div class="container">
        <h1 id="title">Project Novella</h1>
    </div>
</div>